version: "3"

services:
  webserver:
    build:
      context: build/webserver
    container_name: 'lotto-server'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    links:
      - mysql
    volumes:
      - ./www/html:/var/www/html
      - ./dev/config/php/php.ini:/usr/local/etc/php/php.ini
      - ./dev/config/xdebug/xdebug.ini:/etc/php/7.3/mods-available/xdebug.ini
      - ./dev/config/vhosts:/etc/apache2/sites-enabled
      - ./dev/logs/apache2:/var/log/apache2
  mysql:
    build: build/mysql
    container_name: 'lotto-mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes:
      - ./dev/data/mysql:/var/lib/mysql
      - ./dev/logs/mysql:/var/log/mysql
      - ./dev/config/mysql/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_ROOT_PASSWORD: lotto
      MYSQL_DATABASE: lottodb
      MYSQL_USER: lottouser
      MYSQL_PASSWORD: lottosecreat
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'lotto-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes:
      - /sessions