version: "3"

services:
  webserver:
    build:
      context: ./bin/webserver
    container_name: 'lotto-server'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql
    volumes:
      - ./www/public:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-enabled
      - ./logs/apache2:/var/log/apache2
  mysql:
    build: ./bin/mysql
    container_name: 'lotto-mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql}:/var/lib/mysql
      - ./logs/mysql}:/var/log/mysql
      - ./config/mysql/mycustom.cnf}:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_ROOT_PASSWORD: lotto
      MYSQL_DATABASE: lottodb
      MYSQL_USER: lottouser
      MYSQL_PASSWORD: lottosecreat
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'lotto-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes:
      - /sessions